# Generated by Django 2.2.4 on 2019-08-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField()),
                ('capital_gains', models.IntegerField()),
                ('capital_losses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='share_calculator.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.DateTimeField()),
                ('cost_basis', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='share_calculator.Holding')),
            ],
            options={
                'ordering': ['-acquired'],
            },
        ),
    ]
