# Generated by Django 2.2.4 on 2019-08-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_calculator', '0003_auto_20190819_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
