# Generated by Django 2.2.4 on 2019-08-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share_calculator', '0004_auto_20190819_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sale_quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_after_sale', models.DecimalField(decimal_places=2, max_digits=14)),
                ('capital_gains_after_sale', models.DecimalField(decimal_places=2, max_digits=14)),
                ('capital_losses_after_sale', models.DecimalField(decimal_places=2, max_digits=14)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='share_calculator.Holding')),
            ],
        ),
    ]
