# Generated by Django 2.2.4 on 2019-08-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_calculator', '0006_sale_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='account',
            name='net_capital_gains',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
