# Generated by Django 2.2.4 on 2019-08-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_calculator', '0007_auto_20190821_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Sell', max_length=7),
        ),
    ]
