# Generated by Django 2.2.4 on 2019-08-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_calculator', '0008_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_shortterm',
            field=models.BooleanField(default=False),
        ),
    ]
