# Generated by Django 2.2.4 on 2019-12-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_calculator', '0010_auto_20190823_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='target',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
